/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Household Budget Service
 * household budget
 * OpenAPI spec version: 1.0
 */
import type { Income } from "./income";
import type { StoreIncomeValidationError } from "./storeIncomeValidationError";

export interface StoreIncomeResponse {
  income: Income;
  errors: StoreIncomeValidationError;
}
