/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Household Budget Service
 * household budget
 * OpenAPI spec version: 1.0
 */

export interface StoreExpenseInput {
  paidAt: Date;
  amount: number;
  category: number;
  description: string;
}
