/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Household Budget Service
 * household budget
 * OpenAPI spec version: 1.0
 */
import type { Expense } from "./expense";
import type { StoreExpenseValidationError } from "./storeExpenseValidationError";

export interface StoreExpenseResponse {
  expense: Expense;
  errors: StoreExpenseValidationError;
}
