/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Household Budget Service
 * household budget
 * OpenAPI spec version: 1.0
 */
import type { TotalAmountLists } from "./totalAmountLists";

export interface TotalAmountListsResponse {
  totalAmounts: TotalAmountLists[];
}
