/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Household Budget Service
 * household budget
 * OpenAPI spec version: 1.0
 */
import type { TotalAmountListsExtendProps } from "./totalAmountListsExtendProps";

export interface TotalAmountLists {
  date: Date;
  extendProps: TotalAmountListsExtendProps;
}
