// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.3 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
	strictecho "github.com/oapi-codegen/runtime/strictmiddleware/echo"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	AuthenticationScopes = "authentication.Scopes"
)

// Expense Expense
type Expense struct {
	Amount      int                `json:"amount"`
	Category    int                `json:"category"`
	Description string             `json:"description"`
	Id          string             `json:"id"`
	PaidAt      openapi_types.Date `json:"paidAt"`
}

// ExpenseLists Monthly Calender Expense
type ExpenseLists struct {
	Expenses []Expense `json:"expenses"`
}

// StoreExpenseValidationError defines model for StoreExpenseValidationError.
type StoreExpenseValidationError struct {
	Amount      *[]string `json:"amount,omitempty"`
	Category    *[]string `json:"category,omitempty"`
	Description *[]string `json:"description,omitempty"`
	PaidAt      *[]string `json:"paidAt,omitempty"`
}

// TotalAmountLists Total Amount Lists
type TotalAmountLists struct {
	Date        openapi_types.Date `json:"date"`
	ExtendProps struct {
		TotalAmount int    `json:"totalAmount"`
		Type        string `json:"type"`
	} `json:"extendProps"`
}

// UserSignUpValidationError defines model for UserSignUpValidationError.
type UserSignUpValidationError struct {
	Email    *[]string `json:"email,omitempty"`
	Name     *[]string `json:"name,omitempty"`
	Password *[]string `json:"password,omitempty"`
}

// CsrfResponse defines model for CsrfResponse.
type CsrfResponse struct {
	CsrfToken string `json:"csrfToken"`
}

// FetchExpenseListsResponse Monthly Calender Expense
type FetchExpenseListsResponse = ExpenseLists

// InternalServerErrorResponse defines model for InternalServerErrorResponse.
type InternalServerErrorResponse struct {
	Code    int64  `json:"code"`
	Message string `json:"message"`
}

// StoreExpenseResponse defines model for StoreExpenseResponse.
type StoreExpenseResponse struct {
	Errors StoreExpenseValidationError `json:"errors"`

	// Expense Expense
	Expense Expense `json:"expense"`
}

// TotalAmountListsResponse defines model for TotalAmountListsResponse.
type TotalAmountListsResponse struct {
	TotalAmounts []TotalAmountLists `json:"totalAmounts"`
}

// UserSignInBadRequestResponse defines model for UserSignInBadRequestResponse.
type UserSignInBadRequestResponse struct {
	Errors []string `json:"errors"`
}

// UserSignInOkResponse defines model for UserSignInOkResponse.
type UserSignInOkResponse = map[string]interface{}

// UserSignUpResponse defines model for UserSignUpResponse.
type UserSignUpResponse struct {
	Code   int                       `json:"code"`
	Errors UserSignUpValidationError `json:"errors"`
}

// StoreExpenseInput defines model for StoreExpenseInput.
type StoreExpenseInput struct {
	Amount      int                `json:"amount"`
	Category    int                `json:"category"`
	Description string             `json:"description"`
	PaidAt      openapi_types.Date `json:"paidAt"`
}

// UserSignInInput defines model for UserSignInInput.
type UserSignInInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

// UserSignUpInput defines model for UserSignUpInput.
type UserSignUpInput struct {
	Email    string `json:"email"`
	Name     string `json:"name"`
	Password string `json:"password"`
}

// GetExpensesParams defines parameters for GetExpenses.
type GetExpensesParams struct {
	// FromDate 取得対象の日付FROM
	FromDate *string `form:"fromDate,omitempty" json:"fromDate,omitempty"`

	// ToDate 取得対象の日付TO
	ToDate *string `form:"toDate,omitempty" json:"toDate,omitempty"`
}

// PostExpensesJSONBody defines parameters for PostExpenses.
type PostExpensesJSONBody struct {
	Amount      int                `json:"amount"`
	Category    int                `json:"category"`
	Description string             `json:"description"`
	PaidAt      openapi_types.Date `json:"paidAt"`
}

// GetExpensesTotalAmountsParams defines parameters for GetExpensesTotalAmounts.
type GetExpensesTotalAmountsParams struct {
	// FromDate 取得対象の日付FROM
	FromDate string `form:"fromDate" json:"fromDate"`

	// ToDate 取得対象の日付TO
	ToDate string `form:"toDate" json:"toDate"`
}

// PostUsersSignInJSONBody defines parameters for PostUsersSignIn.
type PostUsersSignInJSONBody struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

// PostUsersSignUpJSONBody defines parameters for PostUsersSignUp.
type PostUsersSignUpJSONBody struct {
	Email    string `json:"email"`
	Name     string `json:"name"`
	Password string `json:"password"`
}

// PostUsersValidateSignUpJSONBody defines parameters for PostUsersValidateSignUp.
type PostUsersValidateSignUpJSONBody struct {
	Email    string `json:"email"`
	Name     string `json:"name"`
	Password string `json:"password"`
}

// PostExpensesJSONRequestBody defines body for PostExpenses for application/json ContentType.
type PostExpensesJSONRequestBody PostExpensesJSONBody

// PostUsersSignInJSONRequestBody defines body for PostUsersSignIn for application/json ContentType.
type PostUsersSignInJSONRequestBody PostUsersSignInJSONBody

// PostUsersSignUpJSONRequestBody defines body for PostUsersSignUp for application/json ContentType.
type PostUsersSignUpJSONRequestBody PostUsersSignUpJSONBody

// PostUsersValidateSignUpJSONRequestBody defines body for PostUsersValidateSignUp for application/json ContentType.
type PostUsersValidateSignUpJSONRequestBody PostUsersValidateSignUpJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get Csrf
	// (GET /csrf)
	GetCsrf(ctx echo.Context) error
	// Get Expenses
	// (GET /expenses)
	GetExpenses(ctx echo.Context, params GetExpensesParams) error
	// Post Expense
	// (POST /expenses)
	PostExpenses(ctx echo.Context) error
	// Get Expenses TotalAmounts
	// (GET /expenses/totalAmounts)
	GetExpensesTotalAmounts(ctx echo.Context, params GetExpensesTotalAmountsParams) error
	// User CheckSignedIn
	// (GET /users/checkSignedIn)
	GetUsersCheckSignedIn(ctx echo.Context) error
	// User SignIn
	// (POST /users/signIn)
	PostUsersSignIn(ctx echo.Context) error
	// User SignUp
	// (POST /users/signUp)
	PostUsersSignUp(ctx echo.Context) error
	// User Validate SignUp
	// (POST /users/validateSignUp)
	PostUsersValidateSignUp(ctx echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// GetCsrf converts echo context to params.
func (w *ServerInterfaceWrapper) GetCsrf(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetCsrf(ctx)
	return err
}

// GetExpenses converts echo context to params.
func (w *ServerInterfaceWrapper) GetExpenses(ctx echo.Context) error {
	var err error

	ctx.Set(AuthenticationScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetExpensesParams
	// ------------- Optional query parameter "fromDate" -------------

	err = runtime.BindQueryParameter("form", true, false, "fromDate", ctx.QueryParams(), &params.FromDate)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter fromDate: %s", err))
	}

	// ------------- Optional query parameter "toDate" -------------

	err = runtime.BindQueryParameter("form", true, false, "toDate", ctx.QueryParams(), &params.ToDate)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter toDate: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetExpenses(ctx, params)
	return err
}

// PostExpenses converts echo context to params.
func (w *ServerInterfaceWrapper) PostExpenses(ctx echo.Context) error {
	var err error

	ctx.Set(AuthenticationScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostExpenses(ctx)
	return err
}

// GetExpensesTotalAmounts converts echo context to params.
func (w *ServerInterfaceWrapper) GetExpensesTotalAmounts(ctx echo.Context) error {
	var err error

	ctx.Set(AuthenticationScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetExpensesTotalAmountsParams
	// ------------- Required query parameter "fromDate" -------------

	err = runtime.BindQueryParameter("form", true, true, "fromDate", ctx.QueryParams(), &params.FromDate)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter fromDate: %s", err))
	}

	// ------------- Required query parameter "toDate" -------------

	err = runtime.BindQueryParameter("form", true, true, "toDate", ctx.QueryParams(), &params.ToDate)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter toDate: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetExpensesTotalAmounts(ctx, params)
	return err
}

// GetUsersCheckSignedIn converts echo context to params.
func (w *ServerInterfaceWrapper) GetUsersCheckSignedIn(ctx echo.Context) error {
	var err error

	ctx.Set(AuthenticationScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetUsersCheckSignedIn(ctx)
	return err
}

// PostUsersSignIn converts echo context to params.
func (w *ServerInterfaceWrapper) PostUsersSignIn(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostUsersSignIn(ctx)
	return err
}

// PostUsersSignUp converts echo context to params.
func (w *ServerInterfaceWrapper) PostUsersSignUp(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostUsersSignUp(ctx)
	return err
}

// PostUsersValidateSignUp converts echo context to params.
func (w *ServerInterfaceWrapper) PostUsersValidateSignUp(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostUsersValidateSignUp(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/csrf", wrapper.GetCsrf)
	router.GET(baseURL+"/expenses", wrapper.GetExpenses)
	router.POST(baseURL+"/expenses", wrapper.PostExpenses)
	router.GET(baseURL+"/expenses/totalAmounts", wrapper.GetExpensesTotalAmounts)
	router.GET(baseURL+"/users/checkSignedIn", wrapper.GetUsersCheckSignedIn)
	router.POST(baseURL+"/users/signIn", wrapper.PostUsersSignIn)
	router.POST(baseURL+"/users/signUp", wrapper.PostUsersSignUp)
	router.POST(baseURL+"/users/validateSignUp", wrapper.PostUsersValidateSignUp)

}

type CsrfResponseJSONResponse struct {
	CsrfToken string `json:"csrfToken"`
}

type FetchExpenseListsResponseJSONResponse ExpenseLists

type InternalServerErrorResponseJSONResponse struct {
	Code    int64  `json:"code"`
	Message string `json:"message"`
}

type StoreExpenseResponseJSONResponse struct {
	Errors StoreExpenseValidationError `json:"errors"`

	// Expense Expense
	Expense Expense `json:"expense"`
}

type TotalAmountListsResponseJSONResponse struct {
	TotalAmounts []TotalAmountLists `json:"totalAmounts"`
}

type UserSignInBadRequestResponseJSONResponse struct {
	Errors []string `json:"errors"`
}

type UserSignInOkResponseResponseHeaders struct {
	SetCookie string
}
type UserSignInOkResponseJSONResponse struct {
	Body map[string]interface{}

	Headers UserSignInOkResponseResponseHeaders
}

type UserSignUpResponseJSONResponse struct {
	Code   int                       `json:"code"`
	Errors UserSignUpValidationError `json:"errors"`
}

type GetCsrfRequestObject struct {
}

type GetCsrfResponseObject interface {
	VisitGetCsrfResponse(w http.ResponseWriter) error
}

type GetCsrf200JSONResponse struct{ CsrfResponseJSONResponse }

func (response GetCsrf200JSONResponse) VisitGetCsrfResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetCsrf500JSONResponse struct {
	InternalServerErrorResponseJSONResponse
}

func (response GetCsrf500JSONResponse) VisitGetCsrfResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetExpensesRequestObject struct {
	Params GetExpensesParams
}

type GetExpensesResponseObject interface {
	VisitGetExpensesResponse(w http.ResponseWriter) error
}

type GetExpenses200JSONResponse struct {
	FetchExpenseListsResponseJSONResponse
}

func (response GetExpenses200JSONResponse) VisitGetExpensesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostExpensesRequestObject struct {
	Body *PostExpensesJSONRequestBody
}

type PostExpensesResponseObject interface {
	VisitPostExpensesResponse(w http.ResponseWriter) error
}

type PostExpenses200JSONResponse struct {
	StoreExpenseResponseJSONResponse
}

func (response PostExpenses200JSONResponse) VisitPostExpensesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetExpensesTotalAmountsRequestObject struct {
	Params GetExpensesTotalAmountsParams
}

type GetExpensesTotalAmountsResponseObject interface {
	VisitGetExpensesTotalAmountsResponse(w http.ResponseWriter) error
}

type GetExpensesTotalAmounts200JSONResponse struct {
	TotalAmountListsResponseJSONResponse
}

func (response GetExpensesTotalAmounts200JSONResponse) VisitGetExpensesTotalAmountsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetUsersCheckSignedInRequestObject struct {
}

type GetUsersCheckSignedInResponseObject interface {
	VisitGetUsersCheckSignedInResponse(w http.ResponseWriter) error
}

type GetUsersCheckSignedIn200JSONResponse bool

func (response GetUsersCheckSignedIn200JSONResponse) VisitGetUsersCheckSignedInResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostUsersSignInRequestObject struct {
	Body *PostUsersSignInJSONRequestBody
}

type PostUsersSignInResponseObject interface {
	VisitPostUsersSignInResponse(w http.ResponseWriter) error
}

type PostUsersSignIn200JSONResponse struct {
	UserSignInOkResponseJSONResponse
}

func (response PostUsersSignIn200JSONResponse) VisitPostUsersSignInResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("Set-Cookie", fmt.Sprint(response.Headers.SetCookie))
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response.Body)
}

type PostUsersSignIn400JSONResponse struct {
	UserSignInBadRequestResponseJSONResponse
}

func (response PostUsersSignIn400JSONResponse) VisitPostUsersSignInResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type PostUsersSignIn500JSONResponse struct {
	InternalServerErrorResponseJSONResponse
}

func (response PostUsersSignIn500JSONResponse) VisitPostUsersSignInResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type PostUsersSignUpRequestObject struct {
	Body *PostUsersSignUpJSONRequestBody
}

type PostUsersSignUpResponseObject interface {
	VisitPostUsersSignUpResponse(w http.ResponseWriter) error
}

type PostUsersSignUp200JSONResponse struct{ UserSignUpResponseJSONResponse }

func (response PostUsersSignUp200JSONResponse) VisitPostUsersSignUpResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostUsersSignUp400JSONResponse struct {
	Code   int                       `json:"code"`
	Errors UserSignUpValidationError `json:"errors"`
}

func (response PostUsersSignUp400JSONResponse) VisitPostUsersSignUpResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type PostUsersSignUp500JSONResponse struct {
	InternalServerErrorResponseJSONResponse
}

func (response PostUsersSignUp500JSONResponse) VisitPostUsersSignUpResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type PostUsersValidateSignUpRequestObject struct {
	Body *PostUsersValidateSignUpJSONRequestBody
}

type PostUsersValidateSignUpResponseObject interface {
	VisitPostUsersValidateSignUpResponse(w http.ResponseWriter) error
}

type PostUsersValidateSignUp200JSONResponse struct{ UserSignUpResponseJSONResponse }

func (response PostUsersValidateSignUp200JSONResponse) VisitPostUsersValidateSignUpResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostUsersValidateSignUp400JSONResponse struct {
	Code   int                       `json:"code"`
	Errors UserSignUpValidationError `json:"errors"`
}

func (response PostUsersValidateSignUp400JSONResponse) VisitPostUsersValidateSignUpResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type PostUsersValidateSignUp500JSONResponse struct {
	InternalServerErrorResponseJSONResponse
}

func (response PostUsersValidateSignUp500JSONResponse) VisitPostUsersValidateSignUpResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Get Csrf
	// (GET /csrf)
	GetCsrf(ctx context.Context, request GetCsrfRequestObject) (GetCsrfResponseObject, error)
	// Get Expenses
	// (GET /expenses)
	GetExpenses(ctx context.Context, request GetExpensesRequestObject) (GetExpensesResponseObject, error)
	// Post Expense
	// (POST /expenses)
	PostExpenses(ctx context.Context, request PostExpensesRequestObject) (PostExpensesResponseObject, error)
	// Get Expenses TotalAmounts
	// (GET /expenses/totalAmounts)
	GetExpensesTotalAmounts(ctx context.Context, request GetExpensesTotalAmountsRequestObject) (GetExpensesTotalAmountsResponseObject, error)
	// User CheckSignedIn
	// (GET /users/checkSignedIn)
	GetUsersCheckSignedIn(ctx context.Context, request GetUsersCheckSignedInRequestObject) (GetUsersCheckSignedInResponseObject, error)
	// User SignIn
	// (POST /users/signIn)
	PostUsersSignIn(ctx context.Context, request PostUsersSignInRequestObject) (PostUsersSignInResponseObject, error)
	// User SignUp
	// (POST /users/signUp)
	PostUsersSignUp(ctx context.Context, request PostUsersSignUpRequestObject) (PostUsersSignUpResponseObject, error)
	// User Validate SignUp
	// (POST /users/validateSignUp)
	PostUsersValidateSignUp(ctx context.Context, request PostUsersValidateSignUpRequestObject) (PostUsersValidateSignUpResponseObject, error)
}

type StrictHandlerFunc = strictecho.StrictEchoHandlerFunc
type StrictMiddlewareFunc = strictecho.StrictEchoMiddlewareFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// GetCsrf operation middleware
func (sh *strictHandler) GetCsrf(ctx echo.Context) error {
	var request GetCsrfRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetCsrf(ctx.Request().Context(), request.(GetCsrfRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetCsrf")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetCsrfResponseObject); ok {
		return validResponse.VisitGetCsrfResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetExpenses operation middleware
func (sh *strictHandler) GetExpenses(ctx echo.Context, params GetExpensesParams) error {
	var request GetExpensesRequestObject

	request.Params = params

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetExpenses(ctx.Request().Context(), request.(GetExpensesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetExpenses")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetExpensesResponseObject); ok {
		return validResponse.VisitGetExpensesResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// PostExpenses operation middleware
func (sh *strictHandler) PostExpenses(ctx echo.Context) error {
	var request PostExpensesRequestObject

	var body PostExpensesJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PostExpenses(ctx.Request().Context(), request.(PostExpensesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostExpenses")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(PostExpensesResponseObject); ok {
		return validResponse.VisitPostExpensesResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetExpensesTotalAmounts operation middleware
func (sh *strictHandler) GetExpensesTotalAmounts(ctx echo.Context, params GetExpensesTotalAmountsParams) error {
	var request GetExpensesTotalAmountsRequestObject

	request.Params = params

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetExpensesTotalAmounts(ctx.Request().Context(), request.(GetExpensesTotalAmountsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetExpensesTotalAmounts")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetExpensesTotalAmountsResponseObject); ok {
		return validResponse.VisitGetExpensesTotalAmountsResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetUsersCheckSignedIn operation middleware
func (sh *strictHandler) GetUsersCheckSignedIn(ctx echo.Context) error {
	var request GetUsersCheckSignedInRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetUsersCheckSignedIn(ctx.Request().Context(), request.(GetUsersCheckSignedInRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetUsersCheckSignedIn")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetUsersCheckSignedInResponseObject); ok {
		return validResponse.VisitGetUsersCheckSignedInResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// PostUsersSignIn operation middleware
func (sh *strictHandler) PostUsersSignIn(ctx echo.Context) error {
	var request PostUsersSignInRequestObject

	var body PostUsersSignInJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PostUsersSignIn(ctx.Request().Context(), request.(PostUsersSignInRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostUsersSignIn")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(PostUsersSignInResponseObject); ok {
		return validResponse.VisitPostUsersSignInResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// PostUsersSignUp operation middleware
func (sh *strictHandler) PostUsersSignUp(ctx echo.Context) error {
	var request PostUsersSignUpRequestObject

	var body PostUsersSignUpJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PostUsersSignUp(ctx.Request().Context(), request.(PostUsersSignUpRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostUsersSignUp")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(PostUsersSignUpResponseObject); ok {
		return validResponse.VisitPostUsersSignUpResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// PostUsersValidateSignUp operation middleware
func (sh *strictHandler) PostUsersValidateSignUp(ctx echo.Context) error {
	var request PostUsersValidateSignUpRequestObject

	var body PostUsersValidateSignUpJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PostUsersValidateSignUp(ctx.Request().Context(), request.(PostUsersValidateSignUpRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostUsersValidateSignUp")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(PostUsersValidateSignUpResponseObject); ok {
		return validResponse.VisitPostUsersValidateSignUpResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xYwW7jNhN+FYH/f1RXabstFrpl0+zCaBcJ4mQvgQ+MNLa5kUgtSaU1Ah36BL11e+2h",
	"1xY9F9iXaVP0MQqSkkVJlC3ZTk692RJnON/3DWc4ukcRSzNGgUqBwnvE4X0OQr5kMQH9YCoZh9PvMqAC",
	"JjTLpXoYMSqB6p84yxISYUkYDd4JRtUzES0hxepXxlkGXJa+cMpyYyVXGaAQESphARwVPoqwhAXjK/fb",
	"GETESaZ2sRYIyQldqPcZJvGx9jxnPMUShSjGEpDfXlr4GiLhEKPwurLzq9CsOJqbztae2M07iCQqinZY",
	"hiqv5MozZBU+uhLAp2RBJ3Rf/iDFJOnBL8S3jMeOly3ExodlMQSZguAZDF4X2FX2eMAoTmFPxNqFvyfw",
	"q8yb5Bq39i4yRoWJ/UTw+UX5YA8KIsHnl+wW6HZA9dIhEFR8XhWxYu4VyGhZZuk3REixU/T/5zBHIfpf",
	"UNePwLwVge3cFZKOYH1Q9DLvwopwQiVwipMp8Dvgp5wzfgiGWQyNCkGo/PJ5XSKscpOCEHgBA6RQPuv1",
	"Q/SowHkGnafhNeDbJfcAuEFtILZpZm/6Fick1s51cComMG8GKt+tOuVzv4pmfD21GbpkEifHumTvnsFN",
	"lmTtUv8nEtKtpLXjULGVsDDneNXhobHLEA70Dp6xcJyUure8xPGF6d0HTZk1DZ0CvBHnCJXt3lKD6EF5",
	"drsTulFBrHfw0RJwDIaIKchPThi7JeB0va4PRaMxHrBsdavUsINdB9M51u5iNkI77aLcSMVxWleJ5sLT",
	"9fl/qhshiQ96USQx8sfdFolMoIG8xaaPGm2yQ9kbRuUyWXknOAEaq0bRw2FZW4dXrXWR3naIK8ddOCZm",
	"B6ZNbWTDPDC0zDSzYrhVK1uGG9b5MqISVmRtIsPBXaebdHKi2w062aCzeXt6q44ugcbnnGViYzd0Hz/z",
	"ZNv1SL/1G94cZaVpU8Zrh2flX4cjB4/9Fa9/8BieEdVEMiaH6lFlhyzqh+OiUkCUcyJXU3XYy2OWyyVQ",
	"WTYcHYVKpsh0swoRknqkqAPJyNewMlWf0DnrZuOS5QKWLIm9mzxegPSOzydKEJGnKVYnFKEaRXsx8tEd",
	"cGE8ffrsSFHAMqA4IyhEnz9TjxR1cqkxBGroUT+UaXivlnINZxKjEL0GqcYc1BrNPjs66quF63VBY34r",
	"fPTFEKNNE4qtAgqvZzYhr0F6ZaQSL0Q1zaGZMgrsSt6H87Rao8jhOAWpLyjXbXEefvjx4eOHh98+/vP7",
	"z39+/+vfH37564+fXl2cvUG+kf99DrpvlerPOUu/Mkev/3LjD9rl8qxnD8m27jDbRcL+ibalRfcsXM+K",
	"jkAWxZVIdStU55kJhzbnTNji1B/SVv0ArG9tQfdDW7ELF87hcTQNCox14XDQYOdr0B6etiXvpb3+8RK5",
	"biuS5/AUiT18x50SvXfu3SvPvZYcPWrnArgIoiVEt6odQTyhm7RWbUucNFa7IY+d4m4YSwBT1zxChCf0",
	"Zh6h4znRQ2A74ooMjb7BhNDjor5T9BYETYKZK3epCe1PxztVBOf0XPjo+ThjxweGx+6W1lS+VYmrbKAS",
	"V9k+SlTfuvdSwvouMFaHpunTsK8Z62f/ztxKYTpUhbdNg//UGKxGxdwGWbQL5dr00pwn6vItZRYGQcIi",
	"nCyZkOGLoxdHSFW/0r7d/tSl1AMaZ4zo7xxln9N31W6z1Js7lpuguuurxuIwWfecYlb8GwAA//9G0zf9",
	"nBwAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
