// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.3 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
	strictecho "github.com/oapi-codegen/runtime/strictmiddleware/echo"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	AuthenticationScopes = "authentication.Scopes"
)

// CategoryTotalAmountLists Total Amount Lists
type CategoryTotalAmountLists struct {
	Category    int `json:"category"`
	TotalAmount int `json:"totalAmount"`
}

// Expense Expense
type Expense struct {
	Amount      int                `json:"amount"`
	Category    int                `json:"category"`
	Description string             `json:"description"`
	Id          string             `json:"id"`
	PaidAt      openapi_types.Date `json:"paidAt"`
}

// ExpenseLists Monthly Calender Expense
type ExpenseLists struct {
	Expenses []Expense `json:"expenses"`
}

// Income Income
type Income struct {
	Amount     int                `json:"amount"`
	ClientName string             `json:"clientName"`
	Id         string             `json:"id"`
	ReceivedAt openapi_types.Date `json:"receivedAt"`
}

// IncomeLists defines model for IncomeLists.
type IncomeLists struct {
	Incomes []Income `json:"incomes"`
}

// StoreExpenseValidationError defines model for StoreExpenseValidationError.
type StoreExpenseValidationError struct {
	Amount      *[]string `json:"amount,omitempty"`
	Category    *[]string `json:"category,omitempty"`
	Description *[]string `json:"description,omitempty"`
	PaidAt      *[]string `json:"paidAt,omitempty"`
}

// StoreIncomeValidationError Store Income Validation Error
type StoreIncomeValidationError struct {
	Amount     *[]string `json:"amount,omitempty"`
	ClientName *[]string `json:"clientName,omitempty"`
	ReceivedAt *[]string `json:"receivedAt,omitempty"`
}

// TotalAmountLists Total Amount Lists
type TotalAmountLists struct {
	Date        openapi_types.Date `json:"date"`
	ExtendProps struct {
		TotalAmount int    `json:"totalAmount"`
		Type        string `json:"type"`
	} `json:"extendProps"`
}

// UserSignUpValidationError defines model for UserSignUpValidationError.
type UserSignUpValidationError struct {
	Email    *[]string `json:"email,omitempty"`
	Name     *[]string `json:"name,omitempty"`
	Password *[]string `json:"password,omitempty"`
}

// CategoryTotalAmountListsResponse defines model for CategoryTotalAmountListsResponse.
type CategoryTotalAmountListsResponse struct {
	TotalAmounts []CategoryTotalAmountLists `json:"totalAmounts"`
}

// CsrfResponse defines model for CsrfResponse.
type CsrfResponse struct {
	CsrfToken string `json:"csrfToken"`
}

// FetchExpenseListsResponse Monthly Calender Expense
type FetchExpenseListsResponse = ExpenseLists

// FetchIncomeListsResponse defines model for FetchIncomeListsResponse.
type FetchIncomeListsResponse = IncomeLists

// InternalServerErrorResponse defines model for InternalServerErrorResponse.
type InternalServerErrorResponse struct {
	Code    int64  `json:"code"`
	Message string `json:"message"`
}

// StoreExpenseResponse defines model for StoreExpenseResponse.
type StoreExpenseResponse struct {
	Errors StoreExpenseValidationError `json:"errors"`

	// Expense Expense
	Expense Expense `json:"expense"`
}

// StoreIncomeResponse defines model for StoreIncomeResponse.
type StoreIncomeResponse struct {
	// Errors Store Income Validation Error
	Errors StoreIncomeValidationError `json:"errors"`

	// Income Income
	Income Income `json:"income"`
}

// TotalAmountListsResponse defines model for TotalAmountListsResponse.
type TotalAmountListsResponse struct {
	TotalAmounts []TotalAmountLists `json:"totalAmounts"`
}

// UserSignInBadRequestResponse defines model for UserSignInBadRequestResponse.
type UserSignInBadRequestResponse struct {
	Errors []string `json:"errors"`
}

// UserSignInOkResponse defines model for UserSignInOkResponse.
type UserSignInOkResponse = map[string]interface{}

// UserSignUpResponse defines model for UserSignUpResponse.
type UserSignUpResponse struct {
	Code   int                       `json:"code"`
	Errors UserSignUpValidationError `json:"errors"`
}

// StoreExpenseInput defines model for StoreExpenseInput.
type StoreExpenseInput struct {
	Amount      int                `json:"amount"`
	Category    int                `json:"category"`
	Description string             `json:"description"`
	PaidAt      openapi_types.Date `json:"paidAt"`
}

// StoreIncomeInput defines model for StoreIncomeInput.
type StoreIncomeInput struct {
	Amount     int                `json:"amount"`
	ClientName string             `json:"clientName"`
	ReceivedAt openapi_types.Date `json:"receivedAt"`
}

// UserSignInInput defines model for UserSignInInput.
type UserSignInInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

// UserSignUpInput defines model for UserSignUpInput.
type UserSignUpInput struct {
	Email    string `json:"email"`
	Name     string `json:"name"`
	Password string `json:"password"`
}

// GetExpensesParams defines parameters for GetExpenses.
type GetExpensesParams struct {
	// FromDate 取得対象の日付FROM
	FromDate *string `form:"fromDate,omitempty" json:"fromDate,omitempty"`

	// ToDate 取得対象の日付TO
	ToDate *string `form:"toDate,omitempty" json:"toDate,omitempty"`
}

// PostExpensesJSONBody defines parameters for PostExpenses.
type PostExpensesJSONBody struct {
	Amount      int                `json:"amount"`
	Category    int                `json:"category"`
	Description string             `json:"description"`
	PaidAt      openapi_types.Date `json:"paidAt"`
}

// GetExpensesCategoryTotalAmountsParams defines parameters for GetExpensesCategoryTotalAmounts.
type GetExpensesCategoryTotalAmountsParams struct {
	// FromDate 取得対象の日付FROM
	FromDate string `form:"fromDate" json:"fromDate"`

	// ToDate 取得対象の日付TO
	ToDate string `form:"toDate" json:"toDate"`
}

// GetExpensesTotalAmountsParams defines parameters for GetExpensesTotalAmounts.
type GetExpensesTotalAmountsParams struct {
	// FromDate 取得対象の日付FROM
	FromDate string `form:"fromDate" json:"fromDate"`

	// ToDate 取得対象の日付TO
	ToDate string `form:"toDate" json:"toDate"`
}

// GetIncomesParams defines parameters for GetIncomes.
type GetIncomesParams struct {
	// FromDate 取得対象の日付FROM
	FromDate *string `form:"fromDate,omitempty" json:"fromDate,omitempty"`

	// ToDate 取得対象の日付TO
	ToDate *string `form:"toDate,omitempty" json:"toDate,omitempty"`
}

// PostIncomesJSONBody defines parameters for PostIncomes.
type PostIncomesJSONBody struct {
	Amount     int                `json:"amount"`
	ClientName string             `json:"clientName"`
	ReceivedAt openapi_types.Date `json:"receivedAt"`
}

// GetIncomesTotalAmountsParams defines parameters for GetIncomesTotalAmounts.
type GetIncomesTotalAmountsParams struct {
	// FromDate 取得対象の日付FROM
	FromDate string `form:"fromDate" json:"fromDate"`

	// ToDate 取得対象の日付TO
	ToDate string `form:"toDate" json:"toDate"`
}

// PostUsersSignInJSONBody defines parameters for PostUsersSignIn.
type PostUsersSignInJSONBody struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

// PostUsersSignUpJSONBody defines parameters for PostUsersSignUp.
type PostUsersSignUpJSONBody struct {
	Email    string `json:"email"`
	Name     string `json:"name"`
	Password string `json:"password"`
}

// PostUsersValidateSignUpJSONBody defines parameters for PostUsersValidateSignUp.
type PostUsersValidateSignUpJSONBody struct {
	Email    string `json:"email"`
	Name     string `json:"name"`
	Password string `json:"password"`
}

// PostExpensesJSONRequestBody defines body for PostExpenses for application/json ContentType.
type PostExpensesJSONRequestBody PostExpensesJSONBody

// PostIncomesJSONRequestBody defines body for PostIncomes for application/json ContentType.
type PostIncomesJSONRequestBody PostIncomesJSONBody

// PostUsersSignInJSONRequestBody defines body for PostUsersSignIn for application/json ContentType.
type PostUsersSignInJSONRequestBody PostUsersSignInJSONBody

// PostUsersSignUpJSONRequestBody defines body for PostUsersSignUp for application/json ContentType.
type PostUsersSignUpJSONRequestBody PostUsersSignUpJSONBody

// PostUsersValidateSignUpJSONRequestBody defines body for PostUsersValidateSignUp for application/json ContentType.
type PostUsersValidateSignUpJSONRequestBody PostUsersValidateSignUpJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get Csrf
	// (GET /csrf)
	GetCsrf(ctx echo.Context) error
	// Get Expenses
	// (GET /expenses)
	GetExpenses(ctx echo.Context, params GetExpensesParams) error
	// Post Expense
	// (POST /expenses)
	PostExpenses(ctx echo.Context) error
	// Get Expenses Category TotalAmounts
	// (GET /expenses/categoryTotalAmounts)
	GetExpensesCategoryTotalAmounts(ctx echo.Context, params GetExpensesCategoryTotalAmountsParams) error
	// Get Expenses TotalAmounts
	// (GET /expenses/totalAmounts)
	GetExpensesTotalAmounts(ctx echo.Context, params GetExpensesTotalAmountsParams) error
	// Get Incomes
	// (GET /incomes)
	GetIncomes(ctx echo.Context, params GetIncomesParams) error
	// POST Income
	// (POST /incomes)
	PostIncomes(ctx echo.Context) error
	// GET Incomes TotalAmounts
	// (GET /incomes/totalAmounts)
	GetIncomesTotalAmounts(ctx echo.Context, params GetIncomesTotalAmountsParams) error
	// User CheckSignedIn
	// (GET /users/checkSignedIn)
	GetUsersCheckSignedIn(ctx echo.Context) error
	// User SignIn
	// (POST /users/signIn)
	PostUsersSignIn(ctx echo.Context) error
	// User SignUp
	// (POST /users/signUp)
	PostUsersSignUp(ctx echo.Context) error
	// User Validate SignUp
	// (POST /users/validateSignUp)
	PostUsersValidateSignUp(ctx echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// GetCsrf converts echo context to params.
func (w *ServerInterfaceWrapper) GetCsrf(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetCsrf(ctx)
	return err
}

// GetExpenses converts echo context to params.
func (w *ServerInterfaceWrapper) GetExpenses(ctx echo.Context) error {
	var err error

	ctx.Set(AuthenticationScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetExpensesParams
	// ------------- Optional query parameter "fromDate" -------------

	err = runtime.BindQueryParameter("form", true, false, "fromDate", ctx.QueryParams(), &params.FromDate)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter fromDate: %s", err))
	}

	// ------------- Optional query parameter "toDate" -------------

	err = runtime.BindQueryParameter("form", true, false, "toDate", ctx.QueryParams(), &params.ToDate)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter toDate: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetExpenses(ctx, params)
	return err
}

// PostExpenses converts echo context to params.
func (w *ServerInterfaceWrapper) PostExpenses(ctx echo.Context) error {
	var err error

	ctx.Set(AuthenticationScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostExpenses(ctx)
	return err
}

// GetExpensesCategoryTotalAmounts converts echo context to params.
func (w *ServerInterfaceWrapper) GetExpensesCategoryTotalAmounts(ctx echo.Context) error {
	var err error

	ctx.Set(AuthenticationScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetExpensesCategoryTotalAmountsParams
	// ------------- Required query parameter "fromDate" -------------

	err = runtime.BindQueryParameter("form", true, true, "fromDate", ctx.QueryParams(), &params.FromDate)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter fromDate: %s", err))
	}

	// ------------- Required query parameter "toDate" -------------

	err = runtime.BindQueryParameter("form", true, true, "toDate", ctx.QueryParams(), &params.ToDate)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter toDate: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetExpensesCategoryTotalAmounts(ctx, params)
	return err
}

// GetExpensesTotalAmounts converts echo context to params.
func (w *ServerInterfaceWrapper) GetExpensesTotalAmounts(ctx echo.Context) error {
	var err error

	ctx.Set(AuthenticationScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetExpensesTotalAmountsParams
	// ------------- Required query parameter "fromDate" -------------

	err = runtime.BindQueryParameter("form", true, true, "fromDate", ctx.QueryParams(), &params.FromDate)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter fromDate: %s", err))
	}

	// ------------- Required query parameter "toDate" -------------

	err = runtime.BindQueryParameter("form", true, true, "toDate", ctx.QueryParams(), &params.ToDate)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter toDate: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetExpensesTotalAmounts(ctx, params)
	return err
}

// GetIncomes converts echo context to params.
func (w *ServerInterfaceWrapper) GetIncomes(ctx echo.Context) error {
	var err error

	ctx.Set(AuthenticationScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetIncomesParams
	// ------------- Optional query parameter "fromDate" -------------

	err = runtime.BindQueryParameter("form", true, false, "fromDate", ctx.QueryParams(), &params.FromDate)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter fromDate: %s", err))
	}

	// ------------- Optional query parameter "toDate" -------------

	err = runtime.BindQueryParameter("form", true, false, "toDate", ctx.QueryParams(), &params.ToDate)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter toDate: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetIncomes(ctx, params)
	return err
}

// PostIncomes converts echo context to params.
func (w *ServerInterfaceWrapper) PostIncomes(ctx echo.Context) error {
	var err error

	ctx.Set(AuthenticationScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostIncomes(ctx)
	return err
}

// GetIncomesTotalAmounts converts echo context to params.
func (w *ServerInterfaceWrapper) GetIncomesTotalAmounts(ctx echo.Context) error {
	var err error

	ctx.Set(AuthenticationScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetIncomesTotalAmountsParams
	// ------------- Required query parameter "fromDate" -------------

	err = runtime.BindQueryParameter("form", true, true, "fromDate", ctx.QueryParams(), &params.FromDate)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter fromDate: %s", err))
	}

	// ------------- Required query parameter "toDate" -------------

	err = runtime.BindQueryParameter("form", true, true, "toDate", ctx.QueryParams(), &params.ToDate)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter toDate: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetIncomesTotalAmounts(ctx, params)
	return err
}

// GetUsersCheckSignedIn converts echo context to params.
func (w *ServerInterfaceWrapper) GetUsersCheckSignedIn(ctx echo.Context) error {
	var err error

	ctx.Set(AuthenticationScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetUsersCheckSignedIn(ctx)
	return err
}

// PostUsersSignIn converts echo context to params.
func (w *ServerInterfaceWrapper) PostUsersSignIn(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostUsersSignIn(ctx)
	return err
}

// PostUsersSignUp converts echo context to params.
func (w *ServerInterfaceWrapper) PostUsersSignUp(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostUsersSignUp(ctx)
	return err
}

// PostUsersValidateSignUp converts echo context to params.
func (w *ServerInterfaceWrapper) PostUsersValidateSignUp(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostUsersValidateSignUp(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/csrf", wrapper.GetCsrf)
	router.GET(baseURL+"/expenses", wrapper.GetExpenses)
	router.POST(baseURL+"/expenses", wrapper.PostExpenses)
	router.GET(baseURL+"/expenses/categoryTotalAmounts", wrapper.GetExpensesCategoryTotalAmounts)
	router.GET(baseURL+"/expenses/totalAmounts", wrapper.GetExpensesTotalAmounts)
	router.GET(baseURL+"/incomes", wrapper.GetIncomes)
	router.POST(baseURL+"/incomes", wrapper.PostIncomes)
	router.GET(baseURL+"/incomes/totalAmounts", wrapper.GetIncomesTotalAmounts)
	router.GET(baseURL+"/users/checkSignedIn", wrapper.GetUsersCheckSignedIn)
	router.POST(baseURL+"/users/signIn", wrapper.PostUsersSignIn)
	router.POST(baseURL+"/users/signUp", wrapper.PostUsersSignUp)
	router.POST(baseURL+"/users/validateSignUp", wrapper.PostUsersValidateSignUp)

}

type CategoryTotalAmountListsResponseJSONResponse struct {
	TotalAmounts []CategoryTotalAmountLists `json:"totalAmounts"`
}

type CsrfResponseJSONResponse struct {
	CsrfToken string `json:"csrfToken"`
}

type FetchExpenseListsResponseJSONResponse ExpenseLists

type FetchIncomeListsResponseJSONResponse IncomeLists

type InternalServerErrorResponseJSONResponse struct {
	Code    int64  `json:"code"`
	Message string `json:"message"`
}

type StoreExpenseResponseJSONResponse struct {
	Errors StoreExpenseValidationError `json:"errors"`

	// Expense Expense
	Expense Expense `json:"expense"`
}

type StoreIncomeResponseJSONResponse struct {
	// Errors Store Income Validation Error
	Errors StoreIncomeValidationError `json:"errors"`

	// Income Income
	Income Income `json:"income"`
}

type TotalAmountListsResponseJSONResponse struct {
	TotalAmounts []TotalAmountLists `json:"totalAmounts"`
}

type UserSignInBadRequestResponseJSONResponse struct {
	Errors []string `json:"errors"`
}

type UserSignInOkResponseResponseHeaders struct {
	SetCookie string
}
type UserSignInOkResponseJSONResponse struct {
	Body map[string]interface{}

	Headers UserSignInOkResponseResponseHeaders
}

type UserSignUpResponseJSONResponse struct {
	Code   int                       `json:"code"`
	Errors UserSignUpValidationError `json:"errors"`
}

type GetCsrfRequestObject struct {
}

type GetCsrfResponseObject interface {
	VisitGetCsrfResponse(w http.ResponseWriter) error
}

type GetCsrf200JSONResponse struct{ CsrfResponseJSONResponse }

func (response GetCsrf200JSONResponse) VisitGetCsrfResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetCsrf500JSONResponse struct {
	InternalServerErrorResponseJSONResponse
}

func (response GetCsrf500JSONResponse) VisitGetCsrfResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetExpensesRequestObject struct {
	Params GetExpensesParams
}

type GetExpensesResponseObject interface {
	VisitGetExpensesResponse(w http.ResponseWriter) error
}

type GetExpenses200JSONResponse struct {
	FetchExpenseListsResponseJSONResponse
}

func (response GetExpenses200JSONResponse) VisitGetExpensesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostExpensesRequestObject struct {
	Body *PostExpensesJSONRequestBody
}

type PostExpensesResponseObject interface {
	VisitPostExpensesResponse(w http.ResponseWriter) error
}

type PostExpenses200JSONResponse struct {
	StoreExpenseResponseJSONResponse
}

func (response PostExpenses200JSONResponse) VisitPostExpensesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetExpensesCategoryTotalAmountsRequestObject struct {
	Params GetExpensesCategoryTotalAmountsParams
}

type GetExpensesCategoryTotalAmountsResponseObject interface {
	VisitGetExpensesCategoryTotalAmountsResponse(w http.ResponseWriter) error
}

type GetExpensesCategoryTotalAmounts200JSONResponse struct {
	CategoryTotalAmountListsResponseJSONResponse
}

func (response GetExpensesCategoryTotalAmounts200JSONResponse) VisitGetExpensesCategoryTotalAmountsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetExpensesTotalAmountsRequestObject struct {
	Params GetExpensesTotalAmountsParams
}

type GetExpensesTotalAmountsResponseObject interface {
	VisitGetExpensesTotalAmountsResponse(w http.ResponseWriter) error
}

type GetExpensesTotalAmounts200JSONResponse struct {
	TotalAmountListsResponseJSONResponse
}

func (response GetExpensesTotalAmounts200JSONResponse) VisitGetExpensesTotalAmountsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetIncomesRequestObject struct {
	Params GetIncomesParams
}

type GetIncomesResponseObject interface {
	VisitGetIncomesResponse(w http.ResponseWriter) error
}

type GetIncomes200JSONResponse struct {
	FetchIncomeListsResponseJSONResponse
}

func (response GetIncomes200JSONResponse) VisitGetIncomesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostIncomesRequestObject struct {
	Body *PostIncomesJSONRequestBody
}

type PostIncomesResponseObject interface {
	VisitPostIncomesResponse(w http.ResponseWriter) error
}

type PostIncomes200JSONResponse struct {
	StoreIncomeResponseJSONResponse
}

func (response PostIncomes200JSONResponse) VisitPostIncomesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetIncomesTotalAmountsRequestObject struct {
	Params GetIncomesTotalAmountsParams
}

type GetIncomesTotalAmountsResponseObject interface {
	VisitGetIncomesTotalAmountsResponse(w http.ResponseWriter) error
}

type GetIncomesTotalAmounts200JSONResponse struct {
	TotalAmountListsResponseJSONResponse
}

func (response GetIncomesTotalAmounts200JSONResponse) VisitGetIncomesTotalAmountsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetUsersCheckSignedInRequestObject struct {
}

type GetUsersCheckSignedInResponseObject interface {
	VisitGetUsersCheckSignedInResponse(w http.ResponseWriter) error
}

type GetUsersCheckSignedIn200JSONResponse struct {
	IsSignedIn bool `json:"isSignedIn"`
}

func (response GetUsersCheckSignedIn200JSONResponse) VisitGetUsersCheckSignedInResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostUsersSignInRequestObject struct {
	Body *PostUsersSignInJSONRequestBody
}

type PostUsersSignInResponseObject interface {
	VisitPostUsersSignInResponse(w http.ResponseWriter) error
}

type PostUsersSignIn200JSONResponse struct {
	UserSignInOkResponseJSONResponse
}

func (response PostUsersSignIn200JSONResponse) VisitPostUsersSignInResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("Set-Cookie", fmt.Sprint(response.Headers.SetCookie))
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response.Body)
}

type PostUsersSignIn400JSONResponse struct {
	UserSignInBadRequestResponseJSONResponse
}

func (response PostUsersSignIn400JSONResponse) VisitPostUsersSignInResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type PostUsersSignIn500JSONResponse struct {
	InternalServerErrorResponseJSONResponse
}

func (response PostUsersSignIn500JSONResponse) VisitPostUsersSignInResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type PostUsersSignUpRequestObject struct {
	Body *PostUsersSignUpJSONRequestBody
}

type PostUsersSignUpResponseObject interface {
	VisitPostUsersSignUpResponse(w http.ResponseWriter) error
}

type PostUsersSignUp200JSONResponse struct{ UserSignUpResponseJSONResponse }

func (response PostUsersSignUp200JSONResponse) VisitPostUsersSignUpResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostUsersSignUp400JSONResponse struct {
	Code   int                       `json:"code"`
	Errors UserSignUpValidationError `json:"errors"`
}

func (response PostUsersSignUp400JSONResponse) VisitPostUsersSignUpResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type PostUsersSignUp500JSONResponse struct {
	InternalServerErrorResponseJSONResponse
}

func (response PostUsersSignUp500JSONResponse) VisitPostUsersSignUpResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type PostUsersValidateSignUpRequestObject struct {
	Body *PostUsersValidateSignUpJSONRequestBody
}

type PostUsersValidateSignUpResponseObject interface {
	VisitPostUsersValidateSignUpResponse(w http.ResponseWriter) error
}

type PostUsersValidateSignUp200JSONResponse struct{ UserSignUpResponseJSONResponse }

func (response PostUsersValidateSignUp200JSONResponse) VisitPostUsersValidateSignUpResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostUsersValidateSignUp400JSONResponse struct {
	Code   int                       `json:"code"`
	Errors UserSignUpValidationError `json:"errors"`
}

func (response PostUsersValidateSignUp400JSONResponse) VisitPostUsersValidateSignUpResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type PostUsersValidateSignUp500JSONResponse struct {
	InternalServerErrorResponseJSONResponse
}

func (response PostUsersValidateSignUp500JSONResponse) VisitPostUsersValidateSignUpResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Get Csrf
	// (GET /csrf)
	GetCsrf(ctx context.Context, request GetCsrfRequestObject) (GetCsrfResponseObject, error)
	// Get Expenses
	// (GET /expenses)
	GetExpenses(ctx context.Context, request GetExpensesRequestObject) (GetExpensesResponseObject, error)
	// Post Expense
	// (POST /expenses)
	PostExpenses(ctx context.Context, request PostExpensesRequestObject) (PostExpensesResponseObject, error)
	// Get Expenses Category TotalAmounts
	// (GET /expenses/categoryTotalAmounts)
	GetExpensesCategoryTotalAmounts(ctx context.Context, request GetExpensesCategoryTotalAmountsRequestObject) (GetExpensesCategoryTotalAmountsResponseObject, error)
	// Get Expenses TotalAmounts
	// (GET /expenses/totalAmounts)
	GetExpensesTotalAmounts(ctx context.Context, request GetExpensesTotalAmountsRequestObject) (GetExpensesTotalAmountsResponseObject, error)
	// Get Incomes
	// (GET /incomes)
	GetIncomes(ctx context.Context, request GetIncomesRequestObject) (GetIncomesResponseObject, error)
	// POST Income
	// (POST /incomes)
	PostIncomes(ctx context.Context, request PostIncomesRequestObject) (PostIncomesResponseObject, error)
	// GET Incomes TotalAmounts
	// (GET /incomes/totalAmounts)
	GetIncomesTotalAmounts(ctx context.Context, request GetIncomesTotalAmountsRequestObject) (GetIncomesTotalAmountsResponseObject, error)
	// User CheckSignedIn
	// (GET /users/checkSignedIn)
	GetUsersCheckSignedIn(ctx context.Context, request GetUsersCheckSignedInRequestObject) (GetUsersCheckSignedInResponseObject, error)
	// User SignIn
	// (POST /users/signIn)
	PostUsersSignIn(ctx context.Context, request PostUsersSignInRequestObject) (PostUsersSignInResponseObject, error)
	// User SignUp
	// (POST /users/signUp)
	PostUsersSignUp(ctx context.Context, request PostUsersSignUpRequestObject) (PostUsersSignUpResponseObject, error)
	// User Validate SignUp
	// (POST /users/validateSignUp)
	PostUsersValidateSignUp(ctx context.Context, request PostUsersValidateSignUpRequestObject) (PostUsersValidateSignUpResponseObject, error)
}

type StrictHandlerFunc = strictecho.StrictEchoHandlerFunc
type StrictMiddlewareFunc = strictecho.StrictEchoMiddlewareFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// GetCsrf operation middleware
func (sh *strictHandler) GetCsrf(ctx echo.Context) error {
	var request GetCsrfRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetCsrf(ctx.Request().Context(), request.(GetCsrfRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetCsrf")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetCsrfResponseObject); ok {
		return validResponse.VisitGetCsrfResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetExpenses operation middleware
func (sh *strictHandler) GetExpenses(ctx echo.Context, params GetExpensesParams) error {
	var request GetExpensesRequestObject

	request.Params = params

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetExpenses(ctx.Request().Context(), request.(GetExpensesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetExpenses")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetExpensesResponseObject); ok {
		return validResponse.VisitGetExpensesResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// PostExpenses operation middleware
func (sh *strictHandler) PostExpenses(ctx echo.Context) error {
	var request PostExpensesRequestObject

	var body PostExpensesJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PostExpenses(ctx.Request().Context(), request.(PostExpensesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostExpenses")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(PostExpensesResponseObject); ok {
		return validResponse.VisitPostExpensesResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetExpensesCategoryTotalAmounts operation middleware
func (sh *strictHandler) GetExpensesCategoryTotalAmounts(ctx echo.Context, params GetExpensesCategoryTotalAmountsParams) error {
	var request GetExpensesCategoryTotalAmountsRequestObject

	request.Params = params

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetExpensesCategoryTotalAmounts(ctx.Request().Context(), request.(GetExpensesCategoryTotalAmountsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetExpensesCategoryTotalAmounts")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetExpensesCategoryTotalAmountsResponseObject); ok {
		return validResponse.VisitGetExpensesCategoryTotalAmountsResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetExpensesTotalAmounts operation middleware
func (sh *strictHandler) GetExpensesTotalAmounts(ctx echo.Context, params GetExpensesTotalAmountsParams) error {
	var request GetExpensesTotalAmountsRequestObject

	request.Params = params

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetExpensesTotalAmounts(ctx.Request().Context(), request.(GetExpensesTotalAmountsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetExpensesTotalAmounts")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetExpensesTotalAmountsResponseObject); ok {
		return validResponse.VisitGetExpensesTotalAmountsResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetIncomes operation middleware
func (sh *strictHandler) GetIncomes(ctx echo.Context, params GetIncomesParams) error {
	var request GetIncomesRequestObject

	request.Params = params

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetIncomes(ctx.Request().Context(), request.(GetIncomesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetIncomes")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetIncomesResponseObject); ok {
		return validResponse.VisitGetIncomesResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// PostIncomes operation middleware
func (sh *strictHandler) PostIncomes(ctx echo.Context) error {
	var request PostIncomesRequestObject

	var body PostIncomesJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PostIncomes(ctx.Request().Context(), request.(PostIncomesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostIncomes")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(PostIncomesResponseObject); ok {
		return validResponse.VisitPostIncomesResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetIncomesTotalAmounts operation middleware
func (sh *strictHandler) GetIncomesTotalAmounts(ctx echo.Context, params GetIncomesTotalAmountsParams) error {
	var request GetIncomesTotalAmountsRequestObject

	request.Params = params

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetIncomesTotalAmounts(ctx.Request().Context(), request.(GetIncomesTotalAmountsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetIncomesTotalAmounts")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetIncomesTotalAmountsResponseObject); ok {
		return validResponse.VisitGetIncomesTotalAmountsResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetUsersCheckSignedIn operation middleware
func (sh *strictHandler) GetUsersCheckSignedIn(ctx echo.Context) error {
	var request GetUsersCheckSignedInRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetUsersCheckSignedIn(ctx.Request().Context(), request.(GetUsersCheckSignedInRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetUsersCheckSignedIn")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetUsersCheckSignedInResponseObject); ok {
		return validResponse.VisitGetUsersCheckSignedInResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// PostUsersSignIn operation middleware
func (sh *strictHandler) PostUsersSignIn(ctx echo.Context) error {
	var request PostUsersSignInRequestObject

	var body PostUsersSignInJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PostUsersSignIn(ctx.Request().Context(), request.(PostUsersSignInRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostUsersSignIn")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(PostUsersSignInResponseObject); ok {
		return validResponse.VisitPostUsersSignInResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// PostUsersSignUp operation middleware
func (sh *strictHandler) PostUsersSignUp(ctx echo.Context) error {
	var request PostUsersSignUpRequestObject

	var body PostUsersSignUpJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PostUsersSignUp(ctx.Request().Context(), request.(PostUsersSignUpRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostUsersSignUp")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(PostUsersSignUpResponseObject); ok {
		return validResponse.VisitPostUsersSignUpResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// PostUsersValidateSignUp operation middleware
func (sh *strictHandler) PostUsersValidateSignUp(ctx echo.Context) error {
	var request PostUsersValidateSignUpRequestObject

	var body PostUsersValidateSignUpJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PostUsersValidateSignUp(ctx.Request().Context(), request.(PostUsersValidateSignUpRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostUsersValidateSignUp")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(PostUsersValidateSignUpResponseObject); ok {
		return validResponse.VisitPostUsersValidateSignUpResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xaz3LbNhN/FQ6+78hE+r6mnVS3RHUymja1J7Jz8fjAkCsJMQUwAOREzejQJ+it6bWH",
	"XtvpuTN5mTadPkYHAP+ABCGBlOT24JtMYBe7v99idwH4HYrpMqMEiOBo9A4xeL0CLh7TBIP6MBWUwcnb",
	"DAiHCclWQn6MKRFA1M8oy1IcRwJTMnjFKZHfeLyAZSR/ZYxmwESuK1rSlZYS6wzQCGEiYA4MbUIURwLm",
	"lK3bRxPgMcOZXMWYwAXDZC7Hswgnj5TmGWXLSKARSiIBKGxO3YTKRcwgQaPLQi4sTDPsqC96VWqiL19B",
	"LNBm0zRLQxXkWAUarE2oP09ITJfHBTDFQMTX0RJaEWIQA76BXigZsiZS1YL+6GgcKnAuOLApnpMJ2Rcb",
	"WEY4dQQH528oS1oGG45qHYaEj2PShUD7ENiOXWTHc4y4yPb3WKkI93T8IgsmK+W30s4zSri2fZzvpnMq",
	"ovSRipyvMBf8eT5pD1hEpVL9jQUs1Y//MpihEfrPoMpsA62ED1z2SNByfyPGorWFU201H3CKlQK1VKBF",
	"A7VYUHq/CdGYs9kB0Ig5m53TayC7Ka+mevnB2SxghsFPQMSLPMn153IbSabyNpOUBWWetSFV4zrRHMdA",
	"Q7fbvjzT2eZNiABGonQK7AbYCWOUHSIAaAK1zI6J+OxBldqNSrEEzqM5eESK1FnN9wmXwrlAexco92ru",
	"mw3FAfwGucDOfW8u+iJKcaKUK+OkTaBHPAPTLhv597Cwpnu3YCGkw+d2AdJrtuCD1YDftrDQyYV7gJNv",
	"IRObf0shOX4B2VE3qsbpcZQ81137QaOlhMHqLrb62YFks3GqnHB4eXrdy7tORpQrhGgBUQIaiCmIe2NK",
	"rzG0qi5z56bW9R0wpdsZ3G9PV8ZYW7o90XfgTqnIF9rW6MmxXXEt+86641vPgsZOapvQdK06z5mC0kcs",
	"UjA6Nct0C4YQnVSFou7VSVkCbuvIi5ODnoRxgsJux+EcvspzF1qOQHhGiVik62AcpUAS2Ss4MMzLq39y",
	"Luv0rlxVKLbdcUbApCyFzcYnr3IHO7E7CN7nIK9I9jrN52iUXtVxCNHbe1zQLMXzhTJD2orW/HrOxeff",
	"vHozfD1Ua5uNspXedF/gz2rRXuwgtVBreeGkdFtzuOUKxrdA1je6v1QjAfgLVimgQw0vsNoGhgu79r7R",
	"2iK1pq6aHRTKDwB0bUf5y9X3VF/U2mFoAe0gRVJt+N0ZQB5uBJDkjNGMb21+HdVWfdl1UlSjdoVtdBF1",
	"mdxe0zxjz/pUY3eD475E8w8K0jmMzGu3HkHkdqcNSg7ximGxnsr0mG+ZlVgAEXl/qXMsGqFYN6+FR0io",
	"y5/KkAx/CWvd5GEyo3Y0LuiKw4KmSfBylcxBBI/OJpIQvlouI5nWEKq8aE5GIboBxrWm/90fSghoBiTK",
	"MBqhT+7LTxI6sVA+DGLOZvKHFB29k1OZcmciS8xTEGM53rhm/P9w6Koe5bxB7aZtE6JPfYS2XdaYLKDR",
	"5ZUJyFMQQW6piOa8uHdDV1JoYHY0Lj9PijkSHBYtQajzyGWTnI/fff/xw/uPv3z469cff//25z/f//TH",
	"bz88eX76DIWa/tcrUP1bzv6M0eUXeuu5zzKh1yrnp441BN25wlUfCt13jw0u7L1webWxCDIgLkiqWkK5",
	"nylv4eaMcpOc6sVs7XbAeFQb2C9qmz5YtN6jdYZBOmM03i0wmPE6iO2zklcQj9vkjhfYVZkRbAW3Eej+",
	"K/YK/J3vKHvFf1B/rKj42RUOomMY3NHfj/4j0e7HtnFOc/E7yafclap6qWp7hOpFWQVwQVJ5zDXqVB2H",
	"s9PpeVAe4O0aVunsV8LMf2noX8Ea7xzdC1jNSxsdI4K901WOzF22+sez1UnBrTNZ1ZlecWB8EC8gvpYn",
	"KUgmZBvR8sTFx7XZ7Q73vMHH3LQiB/clpSlExL64qib73MBjHnA1P8CkO7Lq2aPpeYGpQrGGKFcPJMpB",
	"Z0+swNQvKX1ySvM/gXqllNb3ok2IHnQTbnlSO/aB0XiH2snERebJxEW2DxPFvy7txYTxEtaVh7ro7aCv",
	"EHOjf6MvZmDqy8KLusAdG95sFMhtoUWpkKp1RV6xFI3QQohsNBikNI7SBeVi9HD4cIhk9svlm0U05mwW",
	"AEkyitVLSF4t1XWNXXLV4i3TtVH2/KKZbhEp+2xbKq9qLUJFvdtcbf4OAAD//3KCjQW8KwAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
