name: Build and Deploy

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  build-and-deploy:
    name: execute
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Auth gcloud CLI
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT }}

      - name: Run Cloud Build
        working-directory: ./
        run: |
          gcloud builds submit --config ./cloudbuild.yaml
